version: '3.1'

services:

  mongo:
    image: mongo
    container_name: '2wp-rsk-mongo-database'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${RSK_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${RSK_DB_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${RSK_DB_NAME}
      MONGO_INITDB_USER: ${RSK_DB_USER}
      MONGO_INITDB_PWD: ${RSK_DB_PASS}
    volumes:
      - ./mongo-init.sh/:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db:/data/db
    ports:
      - '27017-27019:27017-27019'
